package com.who.gisserver.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

// Generated 2014-4-29 21:52:31 by Hibernate Tools 3.4.0.CR1

/**
 * Userinfo generated by hbm2java
 */

@Entity
@Table(name = "userinfo")
@DynamicInsert @DynamicUpdate
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)

public class Userinfo implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "userid", nullable = false)
	private String userid;
	private String username;
	private String userpsw;
	private String userrole;

	public Userinfo() {
	}

	public Userinfo(String userid, String username, String userpsw,
			String userrole) {
		this.userid = userid;
		this.username = username;
		this.userpsw = userpsw;
		this.userrole = userrole;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpsw() {
		return this.userpsw;
	}

	public void setUserpsw(String userpsw) {
		this.userpsw = userpsw;
	}

	public String getUserrole() {
		return this.userrole;
	}

	public void setUserrole(String userrole) {
		this.userrole = userrole;
	}

}
