package com.who.gisserver.model;

// Generated 2014-4-29 21:52:31 by Hibernate Tools 3.4.0.CR1

/**
 * Userrole generated by hbm2java
 */
public class Userrole implements java.io.Serializable {

	private String roleid;
	private String rolename;
	private String roledesc;

	public Userrole() {
	}

	public Userrole(String roleid, String rolename) {
		this.roleid = roleid;
		this.rolename = rolename;
	}

	public Userrole(String roleid, String rolename, String roledesc) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.roledesc = roledesc;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRoledesc() {
		return this.roledesc;
	}

	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

}
